name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_secrets: yes

      - name: Isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

      - name: Lines of code
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/lines.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_history: yes
          plugin_lines_delay: 60

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update metrics [skip ci]"
          git push
